apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: backend-pdb
  namespace: saas-payment
  labels:
    app: backend
    app.kubernetes.io/name: backend
    app.kubernetes.io/part-of: saas-payment-platform
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: backend
